#+TITLE: Standing Desk
#+DATE: <2020-01-28 Tue>

I have recently "acquired" a standing desk after reading so much about it. I use the term acquire loosely here because I just grabbed an old bar desk we have here at my home and put my monitor on top of a box and, lo and behold, a standing desk. The main reason for that were the benefits to posture, hips and back. I have been suffering with serious posture problems for my whole life and, even though everything is much better now after consistently lifting weights and stretching, I still could use some improvements.

** The first days
Well, they sucked hard. For the first 3 or so days I couldn't even stand properly on my feet at the end of the day. I was still sitting a little (on the couch for the lack of a better option in my current "office"), but only 20% of the time. But I decided to stick with it anyway.

It started to get better a week later. I sat down to watch some Udemy videos and realized I wasn't paying as much attention as I was earlier. Then I realized that it was because, while standing, my concentration levels were much higher. I wouldn't feel sleepy, I wouldn't randomly lose focus. And then all of the sudden I realized that, yeah, I should just stay up.

** Conclusion so far
When I'm tackling a hard problem, doing some mindless grind, or writing a blog post, I'd rather sit. Or lay down. Or something in between. But still force myself to be up for at least 30-50% of the time. When I'm learning, or doing something that requires my attention but doesn't require me to problem solve, I go like 90% up 10% sit. It's done wonders for my back as well. Much less soreness, my hips are much less tight, my hamstrings and core feel stronger and my feet don't hurt anymore. I'd definitely recommend trying to stay up.
